image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip install -r ./requirements.txt && ansible-galaxy install -r requirements.yaml
    command: ansible-playbook --skip-tags "become" ./localhost_shim_playbook.yaml
