sudo: required
addons:
  apt:
    packages:
      - python-apt
  if: NOT os = osx
matrix:
  fast_finish: true
  include:
    - name: "Ubuntu Trusty Tair 14.04"
      os: linux
      dist: trusty
    - name: "Ubuntu Xenial Xerus 16.04"
      os: linux
      dist: xenial
  allow_failures:
    - name: "Ubuntu Precise Pangolin 12.04"
      os: linux
      dist: precise
   - name: "OS X"
      os: osx
install:
  - "sudo pip install -r requirements.txt"
  - "ansible-galaxy install -r requirements.yaml"
script:
  - "ansible-lint tasks/*.yaml"
  - "ansible-playbook -e ansible_python_interpreter=/usr/bin/python localhost_shim_playbook.yaml"
