language: python
python: 2.7
sudo: required
matrix:
  fast_finish: true
  include:
    - name: "Ubuntu Precise Pangolin 12.04"
      dist: precise
    - name: "Ubuntu Trusty Tair 14.04"
      dist: trusty
    - name: "Ubuntu Xenial Xerus 16.04"
      dist: xenial
  allow_failures:
    - name: "OS X"
      os: osx
install:
  - "pip install -r requirements.txt"
  - "ansible-galaxy install -r requirements.yaml"
script:
  - "ansible-lint tasks/*.yaml"
  - "ansible-playbook localhost_shim_playbook.yaml"
