---
#    - name: Install github-markdown-toc from GitHub

# TODO add "latest" checking.
#- name: Make /tmp/ temporary folder

- name: Download latest single-file ec2.py script from stable-2.7 branch
  get_url:
    url: https://raw.githubusercontent.com/ansible/ansible/stable-2.7/contrib/inventory/ec2.py
    dest: ~/bin/ec2.py
    mode: 0700

- name: Download latest single-file ec2.ini config from stable-2.7 branch
  get_url:
    url: https://raw.githubusercontent.com/ansible/ansible/stable-2.7/contrib/inventory/ec2.ini
    dest: ~/ec2.ini
    mode: 0600

#- name: Check if it matches last-known file

#- name: Download single-file script from last tested commit
#  get_url:
#    url: https://raw.githubusercontent.com/ekalinin/github-markdown-toc/41236dc086b240a3018484af84896707de6cdf88/gh-md-toc
#    dest: ~/bin/gh-md-toc
#    mode: 0700

#- name: Move file in ~/bin

#- name: Make file executable only for the user
